#include "Users.h"
#include "Message.h"
#include "Listings.h"
#include "Review.h"
using namespace std;

int User::globalUserCount = 0;
int Buyer::totalRegisteredBuyers = 0;
int Seller::totalRegisteredSellers = 0;

// baes class User implementation
User::User(string n) : userID(globalUserCount++), name(n), inboxCount(0)
{
    for (int i = 0; i < 10; ++i)
        inbox[i] = nullptr;
}

User::~User() {
    for (int i = 0; i < inboxCount; i++)
    {
        delete inbox[i];
        inbox[i] = nullptr;
    }
}

int User::getUserID() const {return userID;}
string User::getName() const {return name;}

void User::receiveMessage(Message* msg)
{
    if (inboxCount >= 10)
    {
        cout << "Inbox full." << endl;
        return;
    }
    inbox[inboxCount++] = msg;
}

void User::viewInbox()
{
    if (inboxCount == 0)
    {
        cout << "Inbox is empty." << endl;
        return;
    }
    for (int i = 0; i < inboxCount; ++i)
    {
        inbox[i]->markAsRead();
        inbox[i]->formatMessageThread();
    }
}

// admin class definitions below
Admin::Admin(string uname, int cl, int uptime)
: User(uname), clearanceLevel(cl), actionsLogged(0), systemUpTime(uptime) {}

void Admin::displayDashboard() const
{
    cout << "\n=== ADMIN DASHBOARD ===" << endl;
    cout << "Admin ID: " << userID << "  Name: " << name << endl;
    cout << "Clearance: Level " << clearanceLevel << endl;
}

void Admin::reviewFlaggedContent(Review& flaggedReview)
{
    if (flaggedReview.getIsFlagged())
    {
        cout << "Admin " << name << " reviewing flagged content:" << endl;
        flaggedReview.displayReview();
        actionsLogged++;
    }
    else
    {
        cout << "Review " << flaggedReview.getReviewID() << " is not flagged." << endl;
    }
}

void Admin::banUser(int targetUserID)
{
    if (clearanceLevel < 2)
    {
        cout << "Insufficient clearance to ban users." << endl;
        return;
    }
    cout << "User ID " << targetUserID << " has been banned by Admin " << name << "." << endl;
    actionsLogged++;
}

string Admin::generateSystemReport()
{
    cout << "===== System Report =====" << endl;
    cout << "Active Listings : " << ListingBase::getTotalActiveListings() << endl;
    cout << "Total Buyers    : " << Buyer::getTotalRegisteredBuyers() << endl;
    cout << "Total Sellers   : " << Seller::getTotalRegisteredSellers() << endl;
    cout << "=========================" << endl;
    return "Report generated by " + name;
}

void Admin::resetUserPassword(int targetUserID)
{
    if (clearanceLevel < 2)
    {
        cout << "Insufficient clearance to reset passwords." << endl;
        return;
    }
    cout << "Password for User ID " << targetUserID << " has been reset by Admin " << name << "." << endl;
    actionsLogged++;
}

void Admin::approveListing(ListingBase& listing)
{
    if (listing.getIsApproved())
    {
        cout << "Listing " << listing.getListingID() << " is already approved." << endl;
        return;
    }
    listing.setIsApproved(true);
    cout << "Listing " << listing.getListingID() << " approved by Admin " << name << "." << endl;
    actionsLogged++;
}

void Admin::removeListing(ListingBase& listing)
{
    if (listing.getIsSold())
    {
        cout << "Listing " << listing.getListingID() << " is already sold, cannot remove." << endl;
        return;
    }
    listing.markAsSold();
    cout << "Listing " << listing.getListingID() << " forcefully removed by Admin " << name << "." << endl;
    actionsLogged++;
}

// Buyer definitions below
Buyer::Buyer(string n, string pn, string jd) : User(n), phoneNumber(pn), joinDate(jd), favoriteCount(0)
{
    totalRegisteredBuyers++;
    for (int i = 0; i < 10; ++i)
        favoriteAds[i] = nullptr;
}

Buyer::~Buyer() {}

int Buyer::getTotalRegisteredBuyers() {return totalRegisteredBuyers;}

void Buyer::displayDashboard() const
{
    cout << "\n=== BUYER DASHBOARD ===" << endl;
    cout << "Buyer ID: " << userID << "  Name: " << name << endl;
    cout << "Favorites Saved: " << favoriteCount << endl;
}

void Buyer::addToFavorites(ListingBase* ad)
{
    if (favoriteCount >= 10)
    {
        cout << "Favorite List is full." << endl;
        return;
    }
    favoriteAds[favoriteCount++] = ad;
    cout << "Listing added to Favorites." << endl;
}

void Buyer::removeFromFavorites(int adID)
{
    for (int i = 0; i < favoriteCount; ++i)
    {
        if (favoriteAds[i]->getListingID() == adID)
        {
            for (int j = i; j < favoriteCount - 1; ++j)
                favoriteAds[j] = favoriteAds[j + 1];

            favoriteAds[--favoriteCount] = nullptr;
            cout << "Listing " << adID << " removed from favorites." << endl;
            return;
        }
    }
    cout << "Listing " << adID << " was not found in your favorites." << endl;
}

void Buyer::displayFavorites()
{
    if (favoriteCount == 0)
    {
        cout << "No favorites yet." << endl;
        return;
    }
    for (int i = 0; i < favoriteCount; i++)
    {
        cout << "Favorite " << i + 1 << ":" << endl;
        cout << "Listing ID:\t\t" << favoriteAds[i]->getListingID() << endl;
        cout << "Price:\t\t" << favoriteAds[i]->getAskingPrice() << " PKR" << endl;
        cout << "Location:\t\t" << favoriteAds[i]->getListingLocation() << endl;
    }
}

void Buyer::draftMessage(Seller* seller, string text)
{
    if (seller == nullptr)
    {
        cout << "Invalid seller." << endl;
        return;
    }
    Message* msg = new Message(userID, seller->getUserID(), text, "Now");
    seller->receiveMessage(msg);
    cout << "Message sent to " << seller->getName() << endl;
}

istream& operator>>(istream& in, Buyer& b)
{
    cout << "Enter Buyer Name: ";
    in >> b.name;
    cout << "Enter Phone Number: ";
    in >> b.phoneNumber;
    b.joinDate = "Today"; // "today" is the default
    return in;
}

// seller class stuff is below
Seller::Seller(string n, string contact, string location)
: User(n), contactNumber(contact), locationAddress(location), activeAdsCount(0), reviewCount(0)
{
    totalRegisteredSellers++;
    for (int i = 0; i < 10; ++i)
        reviews[i] = nullptr;
}

Seller::~Seller()
{
    for (int i = 0; i < reviewCount; i++)
        delete reviews[i];
}

int Seller::getTotalRegisteredSellers() {return totalRegisteredSellers;}

void Seller::displayDashboard() const
{
    cout << "\n=== SELLER DASHBOARD ===" << endl;
    cout << "Seller ID: " << userID << "  Name: " << name << endl;
    cout << "Active Ads: " << activeAdsCount << endl;
}

void Seller::incrementActiveAds() {activeAdsCount++;}
void Seller::decrementActiveAds() {activeAdsCount--;}

string Seller::determineSellerType()
{
    if (activeAdsCount <= 1)
        return "New Seller.";
    else if (activeAdsCount <= 5)
        return "Regular Seller.";

    return "Dealership/Power Seller.";
}

bool Seller::canOfferFinancing()
{
    return determineSellerType() == "Dealership/Power Seller.";
}

void Seller::replyToMessage(int messageID, string replyText, Buyer* buyer)
{
    for (int i = 0; i < inboxCount; i++)
    {
        if (inbox[i]->getMessageID() == messageID)
        {
            Message* reply = new Message(userID, inbox[i]->getSenderID(), replyText, "Now");
            buyer->receiveMessage(reply);
            cout << "Reply sent to buyer." << endl;
            return;
        }
    }
    cout << "Message not found." << endl;
}

void Seller::addReview(Review* r)
{
    if (reviewCount >= 10)
    {
        cout << "Review limit reached." << endl;
        return;
    }
    reviews[reviewCount++] = r;
    cout << "Review added." << endl;
}

int Seller::getSenderIDByMessageID(int messageID) const
{
    for (int i = 0; i < inboxCount; i++)
    {
        if (inbox[i]->getMessageID() == messageID)
            return inbox[i]->getSenderID();
    }
    return -1;
}

istream& operator>>(istream& in, Seller& s)
{
    cout << "Enter Seller Name: ";
    in >> s.name;
    cout << "Enter Contact Number: ";
    in >> s.contactNumber;
    cout << "Enter Location: ";
    in >> s.locationAddress;
    return in;
}
