#include "Admin.h"
#include <iostream>
using namespace std;

//constructors
Admin::Admin()
:adminID(0), username("Unknown"), clearanceLevel(1), actionsLogged(0), systemUpTime(0)  {}

Admin::Admin(int id, string uname, int cl, int uptime)
:adminID(id), username(uname), clearanceLevel(cl), actionsLogged(0), systemUpTime(uptime)   {}

//getters
int Admin::getAdminID() const   {return adminID;}
string Admin::getUsername() const   {return username;}
int Admin::getClearanceLevel() const    {return clearanceLevel;}
int Admin::getActionsLogged() const {return actionsLogged;}
int Admin::getSystemUpTime() const  {return systemUpTime;}

//setters
void Admin::setClearanceLevel(int level) { clearanceLevel = level; }

//methods
void Admin::reviewFlaggedContent(Review flaggedReview)
{
    if (flaggedReview.getIsFlagged())
    {
        cout << "Admin " <<username<<" reviewing flagged content:"<<endl;
        flaggedReview.displayReview();
        actionsLogged++;
    }
    else
        cout <<"Review "<<flaggedReview.getReviewID()<<" is not flagged."<<endl;
}

void Admin::banUser(int userID)
{
    if (clearanceLevel< 2)
    {
        cout<< "Insufficient clearance to ban users." <<endl;
        return;
    }
    cout << "User ID "<< userID<<" has been banned by Admin " <<username<< "."<<endl;
    actionsLogged++;
}

string Admin::generateSystemReport()
{
    cout << "===== System Report =====" << endl;
    cout << "Active Listings : "<< AdListing::getTotalActiveListings()<<endl;
    cout << "Total Buyers    : "<< Buyer::getTotalRegisteredBuyers()<<endl;
    cout << "Total Sellers   : "<< Seller::getTotalRegisteredSellers()<<endl;
    cout << "=========================" << endl;
    return "Report generated by " + username;
}

void Admin::resetUserPassword(int userID)
{
    if (clearanceLevel < 2)
    {
        cout << "Insufficient clearance to reset passwords."<<endl;
        return;
    }
    cout << "Password for User ID "<< userID<<" has been reset by Admin "<< username<< "." <<endl;
    actionsLogged++;
}

void Admin::approveListing(AdListing& listing)
{
    if (listing.getIsApproved())
    {
        cout <<"Listing "<< listing.getListingID()<< " is already approved."<< endl;
        return;
    }
    listing.setIsApproved(true);
    cout << "Listing "<< listing.getListingID()<< " approved by Admin "<< username<< "."<<endl;
    actionsLogged++;
}

void Admin::removeListing(AdListing& listing)
{
    if (listing.getIsSold())
    {
        cout <<"Listing "<<listing.getListingID()<< " is already sold, cannot remove."<< endl;
        return;
    }
    listing.markAsSold();
    cout << "Listing " <<listing.getListingID()<< " forcefully removed by Admin "<<username<< "." << endl;
    actionsLogged++;
}